version: "3"

services:
    app:
        build: .
        container_name: 'api'
        ports:
            - "3333:3333"
        volumes:
            - .:/usr/app
        links:
            - mysql:mysql
        depends_on:
            - "mysql"
        command: yarn dev:server
        networks:
            - backend

    mysql:
        image: mysql:latest
        container_name: 'database'
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_DATABASE: signupsms
            MYSQL_ROOT_PASSWORD: test
            MYSQL_USER: root
            DB_HOSTNAME: localhost
        ports:
            - 3306:3306
        networks:
            - backend

networks:
  backend:
    driver: 'bridge'